osx_image: xcode7.3

dist: trusty
sudo: false

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libudev-dev

# Handle git submodules yourself
git:
    depth: 1
    submodules: false

before_install:
  - git --version
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
#  - sed -ie 's/git@github.com:/https:\/\/github.com\//' .gitmodules
#  - git submodule update --init --recursive --depth=1
#  - git submodule update --init --depth=1
  - git submodule update --remote --merge --depth=1

install:
  - nvm install 7
  - yarn install

script:
  - yarn run ciprep
  - yarn run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"