version: 1.0.{build}

platform:
  - x64
  - x86

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

init:
  - git config --global core.autocrlf input

clone_script:
  - cmd: git clone --depth=1 -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
#  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
  - cmd: git clone --depth=1 --branch=master https://github.com/limpkin/mooltipass.git mooltipass

install:
  - ps: Install-Product node 7 $env:PLATFORM
  - yarn install

before_build:

build_script:
  - yarn ciprep
  - ps: if ($env:PLATFORM -like "x86") { $env:APPVEYOR_REPO_NAME=$env:APPVEYOR_REPO_NAME+"-32bit" }
#  - echo %APPVEYOR_REPO_NAME%
#  - dir \
#  - dir %TEMP%
  - dir app
  - yarn release

test: off